# Generated by Django 5.2 on 2025-04-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='numero',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
