# Generated by Django 5.2 on 2025-06-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reservahistorial_cliente_preferencia_notificacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(default='Confirmación de reserva - FoodFusion', max_length=100)),
                ('cuerpo', models.TextField(help_text='Puedes usar los siguientes placeholders: {{ nombre }}, {{ mesa }}, {{ capacidad }}, {{ fecha }}, {{ hora_inicio }}, {{ hora_fin }}')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
